
name: Gitee repos mirror periodic job

on:
#   workflow_dispatch:
  schedule:
    # Runs at 01:00 UTC (9:00 AM Beijing) every day
    - cron:  '0 1 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Mirror the Github organization repos to Gitee.
      uses: Yikun/hub-mirror-action@v1.1
      with:
        src: github/zhkuo24
        dst: gitee/zhkuo24
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        dst_token:  ${{ secrets.GITEE_TOKEN }}
        timeout: 600
        debug: true
        force_update: true
        black_list: "zhkuo24,zhkuo24.github.io,blog,web_tools,iOS-Learn-Demo,wechatrobot,Python-myproject,TWeather"
