name: Sync to Gitee
on: [ push ]
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Black list
      uses: Yikun/hub-mirror-action@master
      with:
        src: github/zhkuo24
        dst: gitee/zhkuo24
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        dst_token: ${{ secrets.GITEE_TOKEN }}
        clone_style: "ssh"
        static_list: ${{ github.event.repository.name }}
        force_update: true
        debug: true
        timeout: '1h'
